services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    restart: always
    environment:
      - PORT=9000
      - ALOR_REFRESH_TOKEN=your_alor_refresh_token_here
      - BYBIT_API_KEY=your_bybit_api_key_here
      - BYBIT_API_SECRET=your_bybit_api_secret_here